### PR TITLE
Fix GAL Ephs

### PR DESCRIPTION
**Pull request by pgrgich**

### CODE REVIEW

**Comment by silverjam** [comment]
Is there a unit test fix that we need to port?

**Comment by silverjam** [comment]
Build is currently failing with a unit test issue:
```
[2020-07-24T01:37:12.918Z] /home/jenkins/workspace/swift-nav_gnss-converters_PR-445/c/tests/check_ubx.c:178:F:UBX_RXM:test_rxm_sfrbx_gal:0: Assertion 'crc == rxm_sfrbx_gal_crc' failed
[2020-07-24T01:37:12.918Z] tests/CMakeFiles/post-build-test-gnss-converters.dir/build.make:57: recipe for target 'tests/CMakeFiles/post-build-test-gnss-converters' failed
[2020-07-24T01:37:12.918Z] make[2]: *** [tests/CMakeFiles/post-build-test-gnss-converters] Error 1
```

**Comment by dgburr** [comment]
> Is there a unit test fix that we need to port?

Yes: https://github.com/swift-nav/gnss-converters/pull/406/files#diff-03034945e5ed17eecf3c576f7aabb527

**Comment by dgburr** [comment]
`diff --git a/c/tests/check_ubx.c b/c/tests/check_ubx.c
index f377640..9ab73e7 100644
--- a/c/tests/check_ubx.c
+++ b/c/tests/check_ubx.c
@@ -159,7 +159,7 @@ static void ubx_sbp_callback_rxm_sfrbx_bds(
   ck_assert(crc == rxm_sfrbx_bds_crc);
 }
 
-static const u16 rxm_sfrbx_gal_crc = 0x09BA;
+static const u16 rxm_sfrbx_gal_crc = 0x4929;
 static void ubx_sbp_callback_rxm_sfrbx_gal(
     u16 msg_id, u8 length, u8 *buff, u16 sender_id, void *context) {
   (void)context;
`

**Comment by pgrgich** [comment]
@dgburr just did it. Thanks for finding the change.

**Comment by nejla-m** [comment]
Hotfix was approved, however let's not merge until we test

**Comment by pgrgich** [comment]
Already merged onto master and will therefore be in v1.2 -> no need to worry about v1.1 any more.

**Pull request merged**
