### PR TITLE
SSR conversions

### PR DESCRIPTION
**Pull request by mfine**
SSR conversions.

/cc @scarcanague

### CODE REVIEW

**Comment by mfine** [comment]
This is having some troubles that I need to dig into - getting some messages out though.

**Comment by mfine** [comment]
Glonass MSG_SSR_ORBIT_CLOCK:

```json
{
  "length": 47,
  "iod_ssr": 0,
  "iod": 3,
  "c1": 0,
  "time": {
    "wn": 1985,
    "tow": 510350
  },
  "preamble": 85,
  "sender": 61440,
  "along": 183,
  "dot_along": 109,
  "radial": 5073,
  "dot_radial": -404,
  "c0": 45116,
  "msg_type": 1500,
  "payload": "jskHAMEHAQMCAAPREwAAtwAAAMH9//9s/v//bQAAANT///88sAAAAAAAAAAAAAA=",
  "update_interval": 2,
  "crc": 11581,
  "sid": {
    "sat": 1,
    "code": 3
  },
  "cross": -575,
  "dot_cross": -44,
  "c2": 0
}
```

**Comment by mfine** [comment]
GPS MSG_SSR_CODE_BIASES:

```json
{
  "length": 40,
  "iod_ssr": 0,
  "time": {
    "wn": 1985,
    "tow": 510350
  },
  "preamble": 85,
  "sender": 61440,
  "msg_type": 1505,
  "payload": "jskHAMEHAQACAAC1/gKU/hO2/gXO/QjQ/QfV/Quo/QnP/Q/I/hDV/g==",
  "update_interval": 2,
  "biases": [
    {
      "value": -331,
      "code": 0
    },
    {
      "value": -364,
      "code": 2
    },
    {
      "value": -330,
      "code": 19
    },
    {
      "value": -562,
      "code": 5
    },
    {
      "value": -560,
      "code": 8
    },
    {
      "value": -555,
      "code": 7
    },
    {
      "value": -600,
      "code": 11
    },
    {
      "value": -561,
      "code": 9
    }
  ],
  "crc": 3250,
  "sid": {
    "sat": 1,
    "code": 0
  }
}
```

**Comment by mfine** [comment]
Conversions are breaking on the array size of 8.

**Comment by mfine** [comment]
Put a workaround to limit and pad out arrays: 8cb4287.

**Comment by mfine** [comment]
GPS MSG_SSR_ORBIT_CLOCK:

```json
{
  "length": 47,
  "iod_ssr": 0,
  "iod": 158,
  "c1": 0,
  "time": {
    "wn": 1985,
    "tow": 512795
  },
  "preamble": 85,
  "sender": 61440,
  "along": 6827,
  "dot_along": -10,
  "radial": 2031,
  "dot_radial": -227,
  "c0": 4039,
  "msg_type": 1500,
  "payload": "G9MHAMEHAQACAJ7vBwAAqxoAAEsDAAAd////9v///yUAAADHDwAAAAAAAAAAAAA=",
  "update_interval": 2,
  "crc": 20260,
  "sid": {
    "sat": 1,
    "code": 0
  },
  "cross": 843,
  "dot_cross": 37,
  "c2": 0
}
```

**Comment by mfine** [comment]
GPS MSG_SSR_CODE_BIASES:

```json
{
  "length": 34,
  "iod_ssr": 0,
  "time": {
    "wn": 1985,
    "tow": 512790
  },
  "preamble": 85,
  "sender": 61440,
  "msg_type": 1505,
  "payload": "FtMHAMEHAQMCAADe/gHl/gJ8/gMu/gAAAAAAAAAAAAAAAA==",
  "update_interval": 2,
  "biases": [
    {
      "value": -290,
      "code": 0
    },
    {
      "value": -283,
      "code": 1
    },
    {
      "value": -388,
      "code": 2
    },
    {
      "value": -466,
      "code": 3
    },
    {
      "value": 0,
      "code": 0
    },
    {
      "value": 0,
      "code": 0
    },
    {
      "value": 0,
      "code": 0
    },
    {
      "value": 0,
      "code": 0
    }
  ],
  "crc": 11208,
  "sid": {
    "sat": 1,
    "code": 3
  }
}
```

**Comment by mfine** [comment]
GPS MSG_SSR_PHASE_BIASES:

```json
{
  "length": 80,
  "yaw": 289,
  "iod_ssr": 0,
  "time": {
    "wn": 1985,
    "tow": 512790
  },
  "preamble": 85,
  "sender": 61440,
  "msg_type": 1510,
  "payload": "FtMHAMEHAQACAAABIQEAAAABAge+/P//CwECB7T+//8OAQIH1/v//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
  "update_interval": 2,
  "biases": [
    {
      "discontinuity_counter": 7,
      "widelane_integer_indicator": 2,
      "bias": -834,
      "code": 0,
      "integer_indicator": 1
    },
    {
      "discontinuity_counter": 7,
      "widelane_integer_indicator": 2,
      "bias": -332,
      "code": 11,
      "integer_indicator": 1
    },
    {
      "discontinuity_counter": 7,
      "widelane_integer_indicator": 2,
      "bias": -1065,
      "code": 14,
      "integer_indicator": 1
    },
    {
      "discontinuity_counter": 0,
      "widelane_integer_indicator": 0,
      "bias": 0,
      "code": 0,
      "integer_indicator": 0
    },
    {
      "discontinuity_counter": 0,
      "widelane_integer_indicator": 0,
      "bias": 0,
      "code": 0,
      "integer_indicator": 0
    },
    {
      "discontinuity_counter": 0,
      "widelane_integer_indicator": 0,
      "bias": 0,
      "code": 0,
      "integer_indicator": 0
    },
    {
      "discontinuity_counter": 0,
      "widelane_integer_indicator": 0,
      "bias": 0,
      "code": 0,
      "integer_indicator": 0
    },
    {
      "discontinuity_counter": 0,
      "widelane_integer_indicator": 0,
      "bias": 0,
      "code": 0,
      "integer_indicator": 0
    }
  ],
  "yaw_rate": 0,
  "crc": 47191,
  "mw_consistency": 1,
  "dispersive_bias": 0,
  "sid": {
    "sat": 1,
    "code": 0
  }
}
```

**Comment by scarcanague** [comment]
Hum this is strange, how can a GLONASS satellite have a GPS code bias (`code = 0` and `code = 1`)

**Pull request merged**
