### PR TITLE
Fix up scaling

### PR DESCRIPTION
**Pull request by mfine**
Fix up the scaling factor - move it outside of the P calculation. Revert P in L calculation.

/cc @denniszollo @ljbade

### CODE REVIEW

**Comment by ljbade** [comment]
Ah that looks better, I wonder how we can test it without need to deploy it to Skylark?

**Comment by mfine** [comment]
If you have a local setup that uses `rtcm32sbp`, can run this branch locally to evaluate it.

**Comment by ljbade** [comment]
hmm I'm currently using the published stack, how do I run a branch version?

**Comment by mfine** [comment]
get this branch (bring in my remote branch), then run `stack install` in the `haskell` directory.

**Comment by ljbade** [comment]
Is there a way to test this with the Piksi console also running? Or another way to both send the sbp and view the logging>

**Comment by mfine** [comment]
@ljbade @denniszollo uses a TCP port and socat.

We can also just pull it in and try it out - you're the only active user

**Comment by ljbade** [comment]
Yeah OK lets just pull it in

**Pull request merged**
