### PR TITLE
Use absolute paths for git submodules.

### PR DESCRIPTION
**Pull request by benjamin0**
Is this correct?

### CODE REVIEW

**Comment by benjaminaltieri** [comment]
@benjamin0 you may need to update your tool to allow submodules outside the root directory since the current logic will only allow `thirdparty/<submodule-repo_name>` per these lines:
https://github.com/swift-nav/ci-jenkins/blob/9fffc65e41f8860e0f6fd8b78539437b305279b5/tools/create-submodule-update.py#L112
https://github.com/swift-nav/ci-jenkins/blob/9fffc65e41f8860e0f6fd8b78539437b305279b5/tools/pyswiftnav/swift_repo.py#L104

**Comment by benjamin0** [comment]
@benjaminaltieri good call, I will fix

**Comment by benjamin0** [comment]
@benjaminaltieri @woodfell @anth-cole  I got it working with https urls - does this mess anything up for buildroot?

**Comment by benjaminaltieri** [comment]
We will need to check things on the buildroot side but shouldn't be a big deal to fix up later

**Pull request merged**
