### PR TITLE
Improve logic around invalid l1 and l2 obs handling

### PR DESCRIPTION
**Pull request by mfine**
Improve the logic around invalid l1 and l2 obs.

/cc @ljbade @anth-cole

### CODE REVIEW

**Comment by ljbade** [comment]
looks good, just need to verify with test data

**Comment by ljbade** [comment]
@mark I found the fix:
```
diff --git a/haskell/src/Data/RTCM3/SBP.hs b/haskell/src/Data/RTCM3/SBP.hs
index b9347b4..a5cad6d 100644
--- a/haskell/src/Data/RTCM3/SBP.hs
+++ b/haskell/src/Data/RTCM3/SBP.hs
@@ -215,16 +215,16 @@ toWn mjd = (mjd - mjdEpoch) `div` 7
 -- See DF011 and DF012 of the RTCM3 spec
 invalid_L1 :: GpsL1Observation -> Bool
 invalid_L1 l1 =
-  l1 ^. gpsL1Observation_pseudorange == 0x80000      ||
-  l1 ^. gpsL1Observation_carrierMinusCode == 0x80000
+  l1 ^. gpsL1Observation_pseudorange == 524288      ||
+  l1 ^. gpsL1Observation_carrierMinusCode == -524288
 
 -- | Determine whether an L1 + L2 RTCM observation is invalid.
 --
 -- See DF011, DF012, and DF018 of the RTCM3 spec
 invalid_L2 :: GpsL2Observation -> Bool
 invalid_L2 l2 =
-  l2 ^. gpsL2Observation_pseudorangeDifference == 0x2000 ||
-  l2 ^. gpsL2Observation_carrierMinusCode == 0x80000
+  l2 ^. gpsL2Observation_pseudorangeDifference == -8192 ||
+  l2 ^. gpsL2Observation_carrierMinusCode == -524288
 
 -- | Construct metric pseudorange (meters!) from L1 RTCM observation.
 --
@@ -543,4 +543,3 @@ newStore = do
   day <- utctDay <$> getCurrentTime
   let wn = fromIntegral $ div (diffDays day (fromGregorian 1980 1 6)) 7
   Store <$> newIORef wn <*> newIORef mempty <*> newIORef mempty
-
```

The explanation is that we store some of the RTCM fields as signed ints. Haskell does not interpret `0x20000` as a two's complement signed number, instead if becomes a unsigned integer. Using the actual negative decimal number `-8192` works however.

**Comment by ljbade** [comment]
@mfine Can you deploy ^ tomorrow morning? Then I will test it against SYM1 CORS again to see if the problem is gone.

**Comment by mfine** [comment]
@ljbade brought in new constants with 0476eec.

**Comment by ljbade** [comment]
awesome

**Pull request merged**
