### PR TITLE
Ignore extra bits in GAL wn

### PR DESCRIPTION
**Pull request by mfine**
GAL wn is 12 bits, while the GPS wn is 10 bits. Ignore the extra GAL bits when converting to GPS wn.

### CODE REVIEW

**Comment by mfine** [comment]
Screen Shot 2019-04-10 at 19 25 57

Screen Shot 2019-04-10 at 19 32 53

Everything is being converted to GPS wn, so the addition here of a 12 bit value is causing problems. Naively mask it off to 10 bits.

**Comment by pgrgich** [comment]
Lgtm.

**Comment by scarcanague** [comment]
Did you check Beidou was OK? It may have a problem too as it is coded on 13 bits:
image

**Comment by mfine** [comment]
@scarcanague I don't know - BDS doesn't use the same kind of approach here as GAL and GPS did. BDS does:

```c
  sbp_bds_eph->toc.wn = gps_adjust_week_cycle(msg_eph->wn, GPS_WEEK_REFERENCE);
```

GPS does:

```c
  sbp_gps_eph->toc.wn = (state->time_from_rover_obs.wn & 0xFC00) + msg_eph->wn;
```

And GAL now does:

```c
  sbp_gal_eph->toc.wn = (state->time_from_rover_obs.wn & 0xFC00) + (msg_eph->wn & 0x3FF);
```

But, should they all do what BDS is doing instead? The `toe.wn` setting (which is correct in GAL) took this approach in GPS:

```c
  sbp_gps_eph->common.toe.wn =
      gps_adjust_week_cycle(msg_eph->wn, GPS_WEEK_REFERENCE);
  gps_time_match_weeks(
      &(gps_time_t){sbp_gps_eph->common.toe.tow, sbp_gps_eph->common.toe.wn},
      &state->time_from_rover_obs);
```

GAL did:

```c
  sbp_gal_eph->common.toe.wn =
      gps_adjust_week_cycle(msg_eph->wn, GPS_WEEK_REFERENCE);
  gps_time_match_weeks(
      &(gps_time_t){sbp_gal_eph->common.toe.tow, sbp_gal_eph->common.toe.wn},
      &state->time_from_rover_obs);
```

BDS did:

```c
  sbp_bds_eph->common.toe.wn =
      gps_adjust_week_cycle(msg_eph->wn, GPS_WEEK_REFERENCE);
```

So it's not clear to me how best to converge things here.

**Comment by scarcanague** [comment]
I would agree that using `gps_adjust_week_cycle` seems more appropriate for all constellations as well as `gps_time_match_weeks` in addition

**Comment by mfine** [comment]
Punted on doing anything further around the other wn's and left it for a ticket: [ORi-482](https://swift-nav.atlassian.net/browse/ORI-482). Remove the no op code.

**Pull request merged**
