### PR TITLE
Update libswiftnav to current master.

### PR DESCRIPTION
**Pull request by martin-swift**
This should be pretty rubber-stamp.  Lots of good fixes in in libswiftnav.

### CODE REVIEW

**Comment by martin-swift** [comment]
This repo has no CI checks on travis...?

**Comment by martin-swift** [comment]
Cool - do any of those fixes in https://github.com/swift-nav/libswiftnav/pull/19 affect anything in gnss-converters?  If so, I'll wait until that is merged.  If not, then we can proceed here.

**Comment by mbavaro** [comment]
I don't think so, they are around applying the satellite clock offset prior to computing the satellite position (rather than after). I don't think `gnss-converters` actually computes any PVT at all?

**Comment by martin-swift** [comment]
yeah, I didn't think so; just wanted to confirm with you.

**Comment by anth-cole** [comment]
👍 - let's merge and I'll cut a new release in anticipation of updating buildroot for the release

**Comment by martin-swift** [comment]
Cool - @anth-cole what did you need to fiddle to get the travis checks to run again?

**Pull request merged**
